from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, inch, landscape
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.pdfbase.ttfonts import TTFont

 
doc = SimpleDocTemplate("quotation.pdf", 
	pagesize=A4, rightMargin=30,leftMargin=30, topMargin=30,bottomMargin=18)

elements = []

dealerLogo="Dealer Logo"
mmiLogo="MMI Logo"
dealerName = "< M/s Dealers Name >"
dealerAddress1 =  "< Dealer Address 1 >"
dealerAddress2 =  "< Dealer Address 2>"
gstNo="< GST No. XXXXXXXXX >"

data1= [
[dealerLogo,dealerName,mmiLogo],
["", dealerAddress1,""],
["",dealerAddress2,""],
["",gstNo,""],
]

datain=[[""],[""],[""]]

vehicleDetail= "Honda Activa 4G"
date="MM DD YYYY"
refno="VAPL-MMI-222-111"
customerName="Shaik Meera"
address="Plot No 12 Survey No 12 Khanapur Road, Belgaum"
mobileNo="9900089848"

data2=[["Quotation / Performa Invoice for < Cash Purchase > / < Financed Purchase >"]]


data3=[["Vehicle Details",vehicleDetail],["Date",date],["Reference No",refno],
		["Customer's Name",customerName],["Address",address],["Mobile",mobileNo]]

vehicleExShowroomRs=""
insuaranceRs=""
teflonCoatingRs=""
extendedWarrantyRs=""
maintananceCost=""
tempCharges=""
regCost=""
roadTax=""
smartCharges=""
HypothecationCharges=""
handlingCharges=""

data4=[["Details","In Rupees"]]
data5=[["1","Vehicle Ex Showroom",vehicleExShowroomRs],
		["2","Insurance (Comprehensive, Nil Depreciation & Cashless Up to Rs. XXXXX )",insuaranceRs],
		["3","Accessories(10)",""],["4","Teflon Coating",teflonCoatingRs],
		["5","Extended Warranty",extendedWarrantyRs],["6","Annual Maintenance Contract",maintananceCost],
		["7","Temporary Passing and other Charges",tempCharges],
		["8","Registration and other Charges",regCost],
		["9","Road Tax",roadTax],["10","Smart Card and other Charges",smartCharges],
		["11","Hypothecation Charges (Only Applicable for Financed Vehicles)",HypothecationCharges],
		["12","Handling Charges",handlingCharges]]

data6=[["Total",""]]

data7=[["You can book this vehicle for a Minimum Booking Amount of < Rs. 1000/- >"]]

data8=[["Note"
"1. Prices prevailing at the time of delivery are applicable."
"2. This quotation is system generated by MOTORMARTINDIA, based on the" 
	"details provided by < M/s. Dealers Name >"
"3. You can make booking through MOTORMARTINDIA at no extra cost, and" 
	"pay balance amount at < M/s. Dealers Name >","For < M/s. Dealers Name > Authorized Signatory"]]

dataAccessory=[["Accessory1","Accessory6"],["Accessory2","Accessory7"],
["Accessory3","Accessory8"],["Accessory4","Accessory9"],["Accessory5","Accessory10"]]

style1= TableStyle([
                       ('GRID', (-2,0), (-2,-1), 0.25, colors.black),
                       ('BOX', (0,0),(-1,-1), 0.25, colors.black),])

style2=TableStyle([
      		 		('GRID', (0,0), (1,6), 1, colors.black),
                    ('ALIGN',(1,1),(-2,-2),'CENTER'),
 					# ('FONTSIZE', (0, 0), (-2, -1), 14), 
					# ('TEXTFONT', (-2, 0), (-2, -1), 'Times-Bold'),
					])

style3= TableStyle([	('ALIGN', (0,0),(-1,-1),'RIGHT'),
						('VALIGN',(-1,-1),(-1,-1),'BOTTOM'),
                       	('INNERGRID', (0,0), (-1,-1), 0.25, colors.black),
                       	('BOX', (0,0), (-1,-1), 0.25, colors.black),])

style4=TableStyle([('BOX',(0,0),(-1,-1),0.25,colors.white)])


#Configure style and word wrap
s = getSampleStyleSheet()
s = s["BodyText"]
s.wordWrap = 'CJK'

d1 = [[Paragraph(cell, s) for cell in row] for row in data1]
din=[[Paragraph(cell, s) for cell in row] for row in datain]
d2=[[Paragraph(cell, s) for cell in row] for row in data2]
d3 = [[Paragraph(cell, s) for cell in row] for row in data3]
d4=[[Paragraph(cell, s) for cell in row] for row in data4]
d5=[[Paragraph(cell, s) for cell in row] for row in data5]
d6=[[Paragraph(cell, s) for cell in row] for row in data6]
d7=[[Paragraph(cell, s) for cell in row] for row in data7]
d8=[[Paragraph(cell, s) for cell in row] for row in data8]

t1=Table(d1)
tin=Table(din)
t2=Table(d2)
t3=Table(d3)
t4=Table(d4)
t5=Table(d5)
t6=Table(d6)
t7=Table(d7)
t8=Table(d8)

lis=[t1,tin,t2,t3,t4,t5,t6,t7,t8]


t1.setStyle(style1)
tin.setStyle(style4)
t2.setStyle(style2)
t3.setStyle(style2)
t4.setStyle(style3)
t6.setStyle(style3)
t5.setStyle(style3)
t7.setStyle(style1)
t8.setStyle(style3)

#Send the data and build the file

for i in range(0,len(lis)):
	elements.append(lis[i])

doc.build(elements)